### ISSUE TITLE
Make flow numbers meaningful

### ISSUE THREAD

**Issue by Robinlovelace** [ATFutures/upthat#14]
Currently the flow numbers are bamboozlingly big. We could modify them in-app but I think it would be better if the input data were updated so that they provide counts of trips per day. You up for doing that @mpadge for the Accra and Kathmandu as you have for NYC?

![image](https://user-images.githubusercontent.com/1825120/68606452-655e9100-04a6-11ea-9a17-67c3e39bd300.png)

https://github.com/moveability/calibration/issues/7#issuecomment-552448603

**Comment by mpadge** [comment]
That's a part of the imminent plan - to use the NYC data to be able to scale the Accra and Kathmandu values to something real. And you're also right that the numbers actually are bamboozingly big - I'll check out what I've done there are rectify.

---

Edit: The main thing is that they are out by a factor that turns out to be 113 / 408,920, so if you just multiply all of them by that, you get roughly there - absolute maximal flows are then 166,000 in a day. This is still too high, but will be reduced to more realistic range in next iteration of main manuscript, because that will allow me to think about the scaling a bit better.

**Comment by mpadge** [comment]
ah shite, see [this `dodgr` issue](https://github.com/ATFutures/dodgr/issues/121) - there's something awry with the internal scaling of the spatial interaction models. I'll fix that tomorrow morning (it has to just be something trivial), but will then have to regenerate layers to get final values according to procedure [i just described](https://github.com/ATFutures/who3/commit/88f64bbcf277d6d7ad372e7fc76d2c7f630d05ec). (But that's all very easy now, and i can generate the bulk of the layers in just a few hours.)

**Comment by mpadge** [comment]
Done in latest version

**Comment by Robinlovelace** [comment]
Heads-up @mpadge I think this is still an issue: we should add units to layer heading. Also, the pedestrian counts in Accra and Kathmandu seem low. You happy for me to re-open? Will open a separate easy-to-fix ticket on rounding.

**Comment by mpadge** [comment]
This can and should stay closed, because the units are all meaningful now, excepting minor #24

**Comment by Robinlovelace** [comment]
Just to clarify, what are the units? Number of people passing on a segment per workday like in the PCT I guess. That should probably go into the legend.

**Comment by mpadge** [comment]
Yep, numbers of people per day

**Comment by Robinlovelace** [comment]
Per working day? Worth adding to the legend? Also it's worth adding info on the exposure layer, e.g. "Relative levels of pollution" or something more specific.

**Comment by mpadge** [comment]
I'll leave you to change legend titles, which is now fortunately easy with [current PR](https://github.com/ATFutures/upthat/pull/27). The "flows" layer are - yes, indeed! - numbers per working day, and the exposure layer is the HEAT-style "Relative Risk" of mortality scaled to total population, and so is "expected mortality". But we need to talk to WHO about exactly how best to interpret that. I'd suggest for the moment just calling it "expected mortality"?
